sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.7

branches:
  only:
    - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install: bundle install
script: bundle exec rake site:deploy --trace
