---

port: 4000
host: 0.0.0.0
safe: false

### site serving configuration ###
exclude:
  - CNAME
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .travis.yml

permalink: / ## disables post output
timezone: Europe/Buchares
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Deschis @Iași"
keywords:    "open-source, conferință, Iași"
description: "Conferință destinată comunității Open-Source din România."
source_link: "https://github.com/info-uaic/deschis.org"
favicon:     ""
touch_icon:  ""
google_analytics_key: ""


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

# Settings for deploy rake task
username:        "info-uaic"
repo:            "deschis.org"
branch:          "master"
relative_source: "../deschis.org/"
destination:     "../deschis.org-pages/"
production_url:  "https://info-uaic.github.io/deschis.org"
source_url:      "https://github.com/info-uaic/deschis.org"
