# Location Block
locationBlockTitle: "Location"
eventLocationName: "Aula Magna Mihai Eminescu"
eventLocationLink: "https://www.uaic.ro/organizare/departamentul-de-marketing-educational-evenimente-si-imagine-academica/oportunitati-pentru-organizarea-evenimentelor/aula-magna-mihai-eminescu/"
eventStreetAddress: "Universitatea Alexandru Ioan Cuza din Iași, Bulevardul Carol I, Nr.11"
eventAddressLocality: "Iași"
eventAddressLocalityRegion: "Iași"
eventPostalCode: "700506"
eventAddressCountry: "Romania"
eventStartTime: "2016-04-15T09:00"
eventDoorTime: "08:00"
eventEndTime: "2016-04-16T18:00"
eventPlaceCoordinates: "47.174524,27.572306"
mapCenterCoordinates: "47.1739673,27.5712438"
mapMobileCenterCoordinates: "47.1741223,27.572034"

# Team Block
teamBlockTitle: "About us"
aboutUs: >
    Finally, the step we've been waiting for has been taken by a large
    amount of tech industry giants and important figures. From the beggining
    of the IT industry, the Open Source trend has been an element of geek legends,
    but the mith becomes reality in a push of the industry towards greater grounds.
    In our enthusiasm, we want to share the beautiful things this old tabu subject has
    to offer in the software industry, with the help, of course, of great minds with
    state of the art skills. So we hope you'll give us the chance to impress in our
    Open Source Camp hosted in Iași, Romania. Join us for tech talks, workshops and 
    an awesome hackthon that will keep you up in excitement.
